### ISSUE TITLE
 -bash: discord.sh: command not found

### ISSUE THREAD

**Issue by Gtadictos21** [NurdTurd/shell-notifier#1]
Hello! I'm trying to make a WebHook so that it announces every time someone SSH to my servers. I installed discord.sh as well as jq, but when I SSH, the console says ` -bash: discord.sh: command not found`.

**Comment by fieu** [comment]
Is it included in your `$PATH`?

Can you provide the output of `which discord.sh`

**Comment by fieu** [comment]
Closed as it's not a `discord.sh` issue.
